### PR TITLE
Make use of forked roles

### PR DESCRIPTION
**Pull request by tersmitten**

### CODE REVIEW

**Comment by ifedapoolarewaju** [comment]
@tersmitten these changes are still breaking deployment [builds](https://travis-ci.org/transloadit/uppy-server/builds/184981690). Is there anything required to do to make it work as expected?

**Comment by tersmitten** [comment]
Yes, If @kvz releases a new version of [freyproject/frey](https://github.com/freyproject/frey) builds shouldn't fail anymore.

**Comment by ifedapoolarewaju** [comment]
@tersmitten would it make sense to revert this merge and wait till the new release is out? Since it's preventing deployment from going through right now.

**Comment by kvz** [comment]
Just released Frey `v0.3.27`, will try to upgrade our projects now

**Comment by kvz** [comment]
@tersmitten besides these replacements:

```
replace "/v(\d+.\d+.\d+)" '/$1' "${freyFile}"
replace "/apt/(\d+.\d+.\d+)" 'apt/1.3.0' "${freyFile}"
```

are there more that I should add?

**Comment by kvz** [comment]
Never mind, I found a good approach now

**Comment by kvz** [comment]
Here's a list of the PRs, please review:

https://github.com/transloadit/uppy-server/pull/10
https://github.com/tus/tusd/pull/85
https://github.com/transloadit/infra-imagemagick/pull/3

**Review by kvz — COMMENTED** [review]
Looking good

**Comment by tersmitten** [comment]
I'll have a look at them

**Comment by kvz** [comment]
Gave you commit access to infra-imagemagick also

**Pull request merged**
