### PR TITLE
Move Frey specific overrides to group_vars file

### PR DESCRIPTION
**Pull request by tersmitten**
For now I put the Frey specific overrides in `infra/group_vars/all/Frey.yml`, it would be way better if Frey would create this file for us.

Some other variables that should reside here are:
* `ansistrano_allow_anonymous_stats`
* `ansistrano_remove_rolled_back`

but there are more, see the `frey-specific-changes` branches of all the forked roles.

### CODE REVIEW

**Comment by kvz** [comment]
I think this file should reside inside Frey itself, would you agree @tersmitten ?

**Comment by tersmitten** [comment]
I rather have it in Frey ([see](https://github.com/freyproject/frey/issues/62)), since it's the same in multiple repositories.

**Comment by tersmitten** [comment]
I'm done

**Comment by kvz** [comment]
Okay so we both agree the vars should go into the Frey repo, and this is just a step towards that? I'll assume yes and merge this already 👍

**Review by kvz — COMMENTED** [review]
👍

**Comment by tersmitten** [comment]
> Okay so we both agree the vars should go into the Frey repo, and this is just a step towards that? I'll assume yes and merge this already

Yes

**Pull request merged**
